### ISSUE TITLE
using-continue python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#10]
Populate loops/using-continue.py with a tutorial and challenge.

**Comment by drentsoft** [comment]
Can I be assigned this please?

**Comment by L-crypt** [comment]
Can I be assigned for it pls??

**Comment by L-crypt** [comment]
I have added the examples and few notes for students to look forward to grab the basics for desired tutorial . Please give it a check . Thank You
