### ISSUE TITLE
[tutorial] pass statement

### ISSUE THREAD

**Issue by deepu14d** [inspirezonetech/TeachMePythonLikeIm5#105]
Along with break and continue statements in loops, we also have pass statement. But it's not that common in use. It
is mainly used in production codes only.  But still it's good to know about it. 
**Description of the tutorial**

About 'pass'
An example
A challenge

...

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by funbeedev** [comment]
We can put in under `loops/using-pass.py`
@deepu14d you're assigned now!

**Comment by deepu14d** [comment]
> We can put it under `loops/using-pass.py` @deepu14d you're assigned now!

Thank you
