### ISSUE TITLE
[tutorial] Set

### ISSUE THREAD

**Issue by Raksha001** [inspirezonetech/TeachMePythonLikeIm5#106]
**Description of the tutorial**
I wish to contribute to Python Sets, how they are created, adding or removing elements from them.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Comment by funbeedev** [comment]
@Raksha001 Thanks for the suggestion! You've been assigned to this issue now

**Comment by Raksha001** [comment]
@funbeedev Can you add the Hackoberfest label, please?

**Comment by Raksha001** [comment]
@sabderemane Thanks for the label! Can you check the code and merge the linked PR if it's valid, please.

**Comment by sabderemane** [comment]
Due to a large amount of reviews, I put the label Hacktoberfest-accepted but the review will be done later

**Comment by Raksha001** [comment]
Alright! Thank you!✨
