### ISSUE TITLE
[tutorial] Python Decorators

### ISSUE THREAD

**Issue by amulyavarshney** [inspirezonetech/TeachMePythonLikeIm5#109]
**Implementing Decorators in Python**
...

**Do you want to be assigned to work on this?**
- [x] YES
- [ ] NO

**Explanation with Use Cases**
...

**Comment by funbeedev** [comment]
@amulyavarshney Assigned

**Comment by amulyavarshney** [comment]
@funbeedev Please review my PR and add it to Hackoctoberfest accepted label.
