### ISSUE TITLE
using-break python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#11]
Populate loops/using-break.py with a tutorial and challenge.

**Comment by Terayza** [comment]
@funbeedev Could I have this task?

**Comment by funbeedev** [comment]
@Terayza  I'll assign you to this after you've completed the other task :)

**Comment by Terayza** [comment]
@funbeedev May I have this now? :)

**Comment by funbeedev** [comment]
yep! @Terayza
