### ISSUE TITLE
[Tutorial] String Reversal Techniques

### ISSUE THREAD

**Issue by photon149** [inspirezonetech/TeachMePythonLikeIm5#111]
**Description**
Mention about the various String Reversal methods and techniques and also define a tutorial section for practicing the same

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
Please count my PR towards Hacktoberfest contribution

**Comment by photon149** [comment]
@funbeedev can you please assign me the same

**Comment by funbeedev** [comment]
Open for hacktoberfest 2022 contributions

**Comment by photon149** [comment]
Sure will do that @funbeedev .
Thanks.

**Comment by funbeedev** [comment]
Still open for anyone to write a tutorial!

**Comment by i-ganza007** [comment]
Hey , I think I can help as well @i-ganza007
