### ISSUE TITLE
[tutorial] Updating tuples

### ISSUE THREAD

**Issue by pushpit-J19** [inspirezonetech/TeachMePythonLikeIm5#113]
**Description of the tutorial**
Tutorial on how to update an already existing tuple which includes adding and removing items from a tuple.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
please accept this issue under Hacktoberfest

**Comment by pushpit-J19** [comment]
@funbeedev kindly assign me this issue

**Comment by funbeedev** [comment]
@pushpit-J19 thanks for the suggestion but we have another PR for tuples.
