### ISSUE TITLE
for-loops python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#12]
Populate loops/for-loops.py with a tutorial and challenge.

**Comment by codeRider686** [comment]
please assign this to me

**Comment by funbeedev** [comment]
you're assigned now! @codeRider686

**Comment by L-crypt** [comment]
Can I try this or its already closed??

**Comment by MayankHora** [comment]
Can I try this or its already closed??

**Comment by sabderemane** [comment]
@MayankHora I'm closing the issue since there is already a tutorial for this, but you can create another issue to improve the existing tutorial if you have an idea in mind.
