### ISSUE TITLE
[tutorial] feature engineering

### ISSUE THREAD

**Issue by ifeomaaaa** [inspirezonetech/TeachMePythonLikeIm5#132]
**describing what feature engineering is and the steps on how to do it**
...

**Do you want to be assigned to work on this?**
(mark [x])
- [x ] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by funbeedev** [comment]
@ifeomaaaa Thanks for your suggestion however we are looking for tutorials and concepts that can be shown through executable code in a Python file. Unfortunately, this doesn't match that category. Please feel free to suggest anything else in relation to Python or you can request to be assigned to an existing issue. Thanks :)
