### ISSUE TITLE
[tutorial] add dataframe to lists

### ISSUE THREAD

**Issue by ifeomaaaa** [inspirezonetech/TeachMePythonLikeIm5#138]
A tutorial on how to create a dataframe from lists
...

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by funbeedev** [comment]
@ifeomaaaa Go ahead and create a tutorial for this. Thanks!

**Comment by ifeomaaaa** [comment]
@funbeedev hi my second attempt to submit my full request failed and I'm not technical enough to understand why. Could you please clarify what I'm doing wrong?

**Comment by ifeomaaaa** [comment]
@funbeedev I keep getting a flake8 syntax error for pip install pandas. Without pip install I get another error saying no module names pandas. How do I fix this so my pull request can run without these failures?

**Comment by ifeomaaaa** [comment]
@funbeedev hello I haven't heard back about my pull request. I have commented out the code that wouldn't run
