### ISSUE TITLE
writing-to-files python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#17]
Populate file-handling/writing-to-files.py with a tutorial and challenge.

**Comment by raghuchandan1** [comment]
I would like to work on this issue

**Comment by funbeedev** [comment]
@raghuchandan1 Please submit the PR for the other issue before I can assign you to this one. thanks.

**Comment by raghuchandan1** [comment]
I have finished reading-files. Can you please check that and assign this to me?

**Comment by funbeedev** [comment]
assigned @raghuchandan1
