### ISSUE TITLE
scanning-files python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#18]
Populate file-handling/scanning-files.py with a tutorial and challenge.

**Comment by raghuchandan1** [comment]
Can you assign this issue to me?

**Comment by funbeedev** [comment]
@raghuchandan1 Please submit the PR for the other issue before I can assign you to this one. thanks.

**Comment by raghuchandan1** [comment]
I have finished reading-files. Can you please check that and assign this to me?
