### ISSUE TITLE
replace function python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#23]
Populate common-built-in-functions/replace.py with a tutorial and challenge.

**Comment by FaMoSi** [comment]
Can I work on this?

**Comment by funbeedev** [comment]
sure @FaMoSi

**Comment by FaMoSi** [comment]
@funbeedev The PR is #51. 
Let me know if everything is ok by merging it or adding the label "hacktoberfest-accepted" to the PR :)

Thank you!

**Comment by Rishabhc711** [comment]
Hey,  I would like to contribute to it too

**Comment by funbeedev** [comment]
> Hey, I would like to contribute to it too

Hi there, check out the issues section and look for issues not already assigned to someone else. Then request to be assigned :)
