### ISSUE TITLE
booleans python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#4]
Populate variables/booleans.py with a tutorial and challenge.

**Comment by Dave3130** [comment]
Hey, can you assign me the issue ..?

**Comment by funbeedev** [comment]
sure @Dave3130

**Comment by Dave3130** [comment]
I am unable to push changes to git
![Uploading Capture.PNG…]()

**Comment by funbeedev** [comment]
> I am unable to push changes to git
> <img alt="Capture" width="462" src="https://user-images.githubusercontent.com/52663557/97668100-45552280-1aa7-11eb-9e63-af31d0f7318c.PNG">

Did you follow the steps detailed on the CONTRIBUTING.md? [click here for the steps](https://github.com/inspirezonetech/TeachMePythonLikeIm5/blob/main/CONTRIBUTING.md#how-to-submit-your-code---step-by-step-guide)
In summary you need to clone the repo, clone it, make your changes, push to your fork then issue the pull request from Github. 
If you are still having trouble after following the steps listed in the CONTRIBUTION.md let me know.

**Comment by funbeedev** [comment]
@Dave3130  any update?

**Comment by Dave3130** [comment]
Done !!
