### ISSUE TITLE
[tutorial] Dictionaries

### ISSUE THREAD

**Issue by drentsoft** [inspirezonetech/TeachMePythonLikeIm5#44]
A basic introduction to declaring, editing and accessing dictionaries and their values.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Comment by funbeedev** [comment]
@drentsoft thanks for the tutorial suggestion. you've been assigned to this now

**Comment by drentsoft** [comment]
Could you please add the hacktoberfest tag to this issue?

**Comment by funbeedev** [comment]
sure, I've added the tag now
