### ISSUE TITLE
[tutorial] Using pip

### ISSUE THREAD

**Issue by drentsoft** [inspirezonetech/TeachMePythonLikeIm5#53]
A tutorial about what pip is, how to install it and how to use it. Unless this is intended to be covered by the importing modules section.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Comment by funbeedev** [comment]
@drentsoft sure go ahead. you can add it as "using-modules/installing-with-pip.py" or something similar
