### ISSUE TITLE
[tutorial] How to use virtual environments

### ISSUE THREAD

**Issue by drentsoft** [inspirezonetech/TeachMePythonLikeIm5#57]
A brief tutorial on why you might want to use virtual environments and how to set them up. Probably as part of using-modules.
...

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Comment by funbeedev** [comment]
@drentsoft go ahead. just a note to keep the tutorial suitable for a beginner :)
