### ISSUE TITLE
comparison operators python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#6]
Populate operators/comparison.py with a tutorial and challenge.

**Comment by Dave3130** [comment]
Can you assignme me ??

**Comment by funbeedev** [comment]
@Dave3130  I can only assign you to one issue at a time. When you've issued a PR for the other issue you can be assigned to this one!

**Comment by jp2373** [comment]
Hey @funbeedev can you assign this to me? I just need one PR for hactoberfest

**Comment by funbeedev** [comment]
assigned now @jp2373

**Comment by funbeedev** [comment]
@jp2373  any update?

**Comment by abhijeetgupto** [comment]
Hi @funbeedev , if this issue is still open , assign it to me . I'll do it !

**Comment by sabderemane** [comment]
@abhijeetgupto assigned now
