### ISSUE TITLE
📢 📢 Hacktoberfest ends on the 31st! Submit your PRs in time if you're still aiming to complete the challenge!! ⌛⌛

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#63]
^ Announcement ^

**Comment by L-crypt** [comment]
I had a doubt like I have submitted the PRs but the count is not updatted on the hacktoberfest profile of mine. Can you please elaborate how the PRs are considered to be successful.

**Comment by funbeedev** [comment]
@L-crypt which PR isn't counting as hacktoberfest?

**Comment by L-crypt** [comment]
Ok I understood. Also #38 is now showing its count .
Check my #43 for the desired changes as well. Thank You 👍

**Comment by sabderemane** [comment]
Hi @funbeedev, I have my PR #47 which is not counting for the hacktoberfest, can you set the label hackoberfest-accepted for this one please ? I think it will solve the issue 🙏

**Comment by funbeedev** [comment]
@sabderemane done. hopefully it counts now!

**Comment by sabderemane** [comment]
@funbeedev doesn't change right now, I will see later, thanks 👍

**Comment by funbeedev** [comment]
@sabderemane Let me know if the status of the PR changes. Can I ask is your PR showing as "Ineligible Repository" ?

**Comment by sabderemane** [comment]
@funbeedev exactly, inelligible repository. Still the same. The others were labelled hacktoberfest-accepted, there still counting. 
That's why I ask you to change. I've got 3 PR on 4 😢

**Comment by funbeedev** [comment]
@sabderemane I checked my own profile and saw I'm having the same problem! And I think I know what is causing it. I raised an issue with the organisers of hacktoberfest here: https://github.com/digitalocean/hacktoberfest/issues/724
Hopefully they resolve it because I'm also falling short on PRs at the moment!
