### ISSUE TITLE
[feature] Update README

### ISSUE THREAD

**Issue by sabderemane** [inspirezonetech/TeachMePythonLikeIm5#67]
**Description**
With the multiple contributions, README is not up-to-date, need to add the new tutorials.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional informations**
I want to add badges if you agree too @funbeedev .

**Comment by funbeedev** [comment]
@sabderemane Great suggestion! Please go ahead and update the README with the tutorials added so far.
You can add the badges too.
