### ISSUE TITLE
[q] Repository marked as ineligible for Hacktoberfest

### ISSUE THREAD

**Issue by drentsoft** [inspirezonetech/TeachMePythonLikeIm5#82]
**Your query**
...
Just checked on the Hacktoberfest progress and they've marked this repository as ineligible. Any ideas why?

**Comment by funbeedev** [comment]
Hi there @drentsoft 
Unfortunately this a problem with the hacktoberfest system that's affecting PRs that were still under review after hacktoberfest ended. I've contacted the organisers of hacktoberfest about this and they acknowledge its a flaw in their logic but I'm still waiting to see if it will be fixed.
It may help if you report the problem at their email: hacktoberfest@digitalocean.com and maybe they will do something about it if more people say its affecting them!

**Comment by drentsoft** [comment]
Thanks @funbeedev I will do.
