### ISSUE TITLE
[tutorial] Improvement to "functions" and "Booleans"

### ISSUE THREAD

**Issue by RenatoLopes771** [inspirezonetech/TeachMePythonLikeIm5#89]
I did some improvements for "functions" and "Booleans". Here's my code: https://github.com/RenatoLopes771/TeachMePythonLikeIm5/commit/61ba6bd2adbfd7287e9ff886d5aca4c1818b4190

Tell me if it's approved so I can request a PR

**Comment by sabderemane** [comment]
Hi @RenatoLopes771 , thanks for your interest !

Sounds correct to me, it's an improvement of a existing tutorial, you can make the PR, we will review it.
