### ISSUE TITLE
while-loops python tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMePythonLikeIm5#9]
Populate loops/while-loops.py with a tutorial and challenge.

**Comment by Dave3130** [comment]
Can I be assigned...?

**Comment by L-crypt** [comment]
Can I be assigned??
Actually I didn't know about the procedure so I added PR for the same

**Comment by L-crypt** [comment]
I have completed the changes as asked. Thank You :)
