### ISSUE TITLE
[tutorial] Lambda Functions

### ISSUE THREAD

**Issue by CyanGirl** [inspirezonetech/TeachMePythonLikeIm5#95]
**Description of the tutorial**

- Definition of Lambda Function and Syntax
- Difference from defined functions
- Examples
- Usage of Lambda
- Challenge

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
The "functions" tutorial can be extended with the Lambda Basic.

**Comment by funbeedev** [comment]
@CyanGirl Thanks for the suggestion! You're assigned to this issue now
